apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.4
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-configuration
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim